version: "3"

services:
  streaming-server:
    build:
      context: .
    environment:
      - STORAGE_TYPE=filesystem
      - VIDEOS_DIRECTORY_PATH=./resources/
      - LISTENING_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./resources/the-big-bang-theory-opening.mp4:/app/resources/the-big-bang-theory-opening.mp4
  html-pages-server:
   image: nginx:alpine
   ports:
      - "9005:80"
   depends_on:
      - streaming-server
   volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html