version: "3"

services:
  mongodb:
    image: mongo:4.0.6
    environment:
      - MONGO_INITDB_DATABASE=streaming
    volumes:
      - ./resources/restore_mongodb_dump.sh:/docker-entrypoint-initdb.d/restore_mongodb_dump.sh
      - ./resources/mongodb_dump:/mongodb_dump
  streaming-server:
    build:
      context: .
    environment:
      - STORAGE_TYPE=database
      - DATABASE_URL=mongodb://mongodb:27017
      - LISTENING_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    volumes:
      - ./resources/wait-for-it.sh:/app/wait-for-it.sh
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "node", "app.js"]

  html-pages-server:
   image: nginx:alpine
   ports:
      - "9005:80"
   depends_on:
      - streaming-server
   volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html